services:
  client:
    restart: always
    image: alskfl222/sv-client:0.5
    ports:
      - 3000:3000
    volumes:
      - ./client/.env:/streamview/client/.env

  server:
    restart: always
    image: alskfl222/sv-server:0.7
    ports:
      - 4000:4000
      - 4004:4004
    volumes:
      - ./server/.env:/streamview/server/.env
      - ./observer/.env:/streamview/observer/.env

  selenium:
    restart: always
    image: selenium/standalone-chrome
    expose:
      - '4444'

