services:
  client:
    image: alskfl222/sv-client:0.2
    ports:
      - 3000:3000
    volumes:
      - ./client/.env:/streamview/client/.env

  server:
    image: alskfl222/sv-server:0.3
    expose:
      - '4000'
      - '4004'
    volumes:
      - ./server/.env:/streamview/server/.env
      - ./observer/.env:/streamview/observer/.env

  selenium:
    restart: always
    image: selenium/standalone-chrome
    expose:
      - '4444'

